### ISSUE TITLE
Achieving many of the microservice benefits in a monolith

### ISSUE THREAD

**Issue by billoneil** [StubbornJava/StubbornJava#96]
Many of the benefits of microservices can also be achieved in a monolith with a little extra work. Many of these should also be applied to microservices as well.

- [ ] [Separation of concerns with modules and visibility](https://github.com/StubbornJava/StubbornJava/issues/92)
- [ ] [Managing timeouts](https://github.com/StubbornJava/StubbornJava/issues/93)
- [ ] [Managing Resource Pools](https://github.com/StubbornJava/StubbornJava/issues/94)
- [ ] [Circuit breaking Misbehaving Services/Endpoints](https://github.com/StubbornJava/StubbornJava/issues/95)
